# Generated by Django 5.0.2 on 2026-01-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="id_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
