# Generated by Django 5.0.2 on 2026-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0002_alter_hotel_city_alter_hotel_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floor",
            options={
                "ordering": ["number"],
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["number"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
            },
        ),
        migrations.RemoveIndex(
            model_name="room",
            name="hostel_room_hotel_i_6e6daf_idx",
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="floor",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name="floor",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="roomtype",
            name="hotel",
        ),
    ]
