# Generated by Django 5.0.2 on 2026-01-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0003_alter_floor_options_alter_room_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="hostel.invoice",
            ),
        ),
    ]
