# Generated by Django 5.0.2 on 2026-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0004_alter_payment_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax percentage (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "default_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default discount percentage (e.g., 5.00 for 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description or notes about these settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["-created_at"],
            },
        ),
    ]
