# Generated by Django 5.0.2 on 2026-01-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CHANGE_PASSWORD", "Change Password"),
                            ("TOGGLE_DELETE", "Toggle Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Entity being acted upon (e.g., User, Group)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Previous values (for updates)", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="New values (for updates)", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who was affected by the action",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="administrat_action_e7ce6e_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-created_at"],
                        name="administrat_perform_a74be7_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="administrat_target__3fe363_idx",
                    ),
                ],
            },
        ),
    ]
