# Generated by Django 5.0.2 on 2026-02-15 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_auditlog_updated_at_auditlog_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('backup_name', models.CharField(help_text='Name/identifier for the backup', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of the backup range')),
                ('end_date', models.DateField(help_text='End date of the backup range')),
                ('file_path', models.CharField(help_text='Path where CSV file is stored', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of backup file in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the backup', max_length=20)),
                ('record_count', models.IntegerField(default=0, help_text='Total records backed up')),
                ('models_backed_up', models.JSONField(default=list, help_text='List of models included in backup')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('requested_by', models.ForeignKey(help_text='User who requested the backup', on_delete=django.db.models.deletion.PROTECT, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='administrat_status_944978_idx'), models.Index(fields=['requested_by', '-created_at'], name='administrat_request_d87abf_idx'), models.Index(fields=['start_date', 'end_date'], name='administrat_start_d_1998aa_idx')],
            },
        ),
    ]
